name: commit
inputs:
  deploy-env:
    required: true
  version:
    required: true
  github-username:
    required: true
  github-pat:
    required: true
  service-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Helm
      run: |
        curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      shell: bash

    - name: Checkout zero-trusted-pipeline repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-pat }}
        repository: "PrrrStar/zero-trusted-pipeline"
        ref: "main"
        path: "zero-trusted-pipeline"

    - name: Set git user name
      run: |
        git config --global user.email "jmeef0802@gmail.com"
        git config --global user.name "${{ inputs.github-username }}"
      shell: bash

    - name: Change version in zero-trusted-pipeline
      env:
        VERSION: ${{ inputs.version }}
        DEPLOY_ENV: ${{ inputs.deploy-env }}
        SERVICE_NAME: ${{ inputs.service-name }}
      run: |
        ROOT=$PWD
        echo $ROOT
        echo $(ls)

        TARGET_CHART_PATH="$ROOT/zero-trusted-pipeline/charts/$SERVICE_NAME"

        cd $TARGET_CHART_PATH

        yq e --inplace '.image.tag = "$VERSION"' values.yaml
        echo "helm template $SERVICE_NAME . --values values.yaml"

        cd $ROOT/zero-trusted-pipeline
        git diff

        set +e
        git commit -am "[Release] Version : $VERSION"
        git push origin main -f
        set -e
      shell: bash